---
title: "Test stopr::find_stops()"
output: 
  html_document:
    keep_md: true
date: "2023-10-16"
editor_options: 
  chunk_output_type: console
---

```{r knitr_setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup

```{r setup}
# Load packages, installing as needed
if (!requireNamespace("pacman", quietly = TRUE)) install.packages("pacman")
pacman::p_load(here, tibble, dplyr, lubridate, readr, scales, sf, knitr)
pacman::p_load_gh("brianhigh/stopr")
pacman::p_load_gh("stadiamaps/ggmap")

# Run a separate script to register the API key to use with Stadia Maps
# See: https://docs.stadiamaps.com/guides/migrating-from-stamen-map-tiles/
# register_stadiamaps("YOUR-API-KEY-HERE")
source(here("reg_api.R"))

# Define variables
gpx_file <- system.file("extdata", "test_data.gpx", package = "stopr")
stop_threshold_secs = 20
bbox_border <- 0.005
bbox_range_fraction <- 0.3
map_zoom <- 15
```

## Load data

```{r load_data}
# Import GPX file
df <- st_read(gpx_file, layer = "track_points", quiet = TRUE) %>% 
  mutate(longitude = st_coordinates(.)[, 'X'], 
         latitude = st_coordinates(.)[, 'Y'], 
         datetime = as_datetime(time))%>%
  as_tibble() %>% select(longitude, latitude, datetime)
```

## Find stops

Given a GPS track (coordinates and timestamps), find the stops on the route.

```{r find_stops}
# Find the stops on the route
stops <- find_stops(df, stop_min_duration_s = stop_threshold_secs)
```

## Show a list of stops

```{r list_stops}
kable(stops)
```

## Create bounding box for map

```{r create_bounding_box}
# Prepare a data frame to use for making the bounding box of the basemap
center_lat <- mean(range(df$latitude))
center_lon <- mean(range(df$longitude))
border <- bbox_border
bbox.df <- data.frame(
  lat = c(center_lat - border, center_lat, center_lat + border),
  lon = c(center_lon - border, center_lon, center_lon + border))
bbox <- make_bbox(lon, lat, bbox.df, f = bbox_range_fraction)
```

## Create base map

```{r create_basemap}
# Create the basemap from Stadia Map's "Toner Lite" tiles
basemap <- get_stadiamap(bbox, zoom = map_zoom, maptype = "stamen_toner_lite")
```

## Create map

```{r create_map}
# Create the map
p <- ggmap(basemap) +
  geom_point(mapping = aes(x = longitude, y = latitude),
             data = df, color = 'orange', size = 1, alpha = 0.6) +
  geom_point(mapping = aes(x = longitude, y = latitude,
                           size = log10(rescale(duration) + 1)/2),
             data = stops, color = 'darkred', alpha = 0.9) +
  theme_void() + theme(legend.position = "none") +
  labs(x = NULL, y = NULL, fill = NULL)
```

## Show map

```{r map, echo=FALSE}
p
```
